import { Contact } from '@app/pages/my-contacts/shared/interfaces/contact';
import { ContactModel } from '@app/pages/my-contacts/shared/model/contact-model';
import { ResourceStatus } from '@app/shared/enum/resource-status.enum';
import { TypeOfPerson } from '@app/shared/enum/type-of-person.enum';

let id = 0;

export const contacts: Contact[] = [
    new ContactModel(
        ++id,
        'Theodore Evelyn Mosby',
        '75260298349',
        new Date(1982, 0, 3),
        TypeOfPerson.NATURAL,
        ResourceStatus.active,
        'PR',
        'Curitiba',
        'Rua Antonio, 563',
        'Tatuquara',
        '81480140',
        '',
        4136464161,
        'ted.mosby@teste.com',
        'Engenharia'
    ),
    new ContactModel(
        ++id,
        'Barney Stinson',
        '91856339505',
        new Date(1978, 4, 3),
        TypeOfPerson.NATURAL,
        ResourceStatus.active,
        'MG',
        'Ipatinga',
        'Rua Ervalia, 964',
        'Bela Vista',
        '35160188',
        '',
        3136457194,
        'barney@teste.com',
        'Financeiro'
    ),
    new ContactModel(
        ++id,
        'Lily Aldrin',
        '52358124761',
        new Date(1984, 2, 3),
        TypeOfPerson.NATURAL,
        ResourceStatus.active,
        'SP',
        'São Paulo',
        'Rua Conselheiro Brotero, 769',
        'Tatuquara',
        '01154000',
        '',
        1126180961,
        'lilizinha@teste.com',
        'Educacional'
    ),

    new ContactModel(
        ++id,
        'Andreia',
        '33109176149',
        new Date(1994, 8, 7),
        TypeOfPerson.NATURAL,
        ResourceStatus.active,
        'SP',
        'Bragança Paulista',
        'Avenida João Alberto Ahnert, 955',
        'Jardim Águas Claras',
        '12929070',
        '',
        1128302252,
        'andreia@madg.com.br',
        'Marketing'
    ),
    new ContactModel(
        ++id,
        'Cristiano',
        '78721316252',
        new Date(1992, 10, 27),
        TypeOfPerson.NATURAL,
        ResourceStatus.active,
        'AM',
        'Manaus',
        'Rua Praia Canoa Quebrada, 740',
        'Tarumã',
        '69041360',
        '',
        9226008589,
        'cristiano@padariabreadcrumb.com.br',
        'Comercial'
    ),
    new ContactModel(
        ++id,
        'Leonel',
        '00062688898',
        new Date(2006, 11, 3),
        TypeOfPerson.NATURAL,
        ResourceStatus.active,
        'SP',
        'São Paulo',
        'Rua Luiza Campanella Giordano, 799',
        'Pq Paineiras',
        '03694180',
        '',
        4136464161,
        'leo.thomaz@teste.com',
        'VENDAS'
    ),
    new ContactModel(
        ++id,
        'Lucas Paro',
        '20939847000143',
        new Date(2002, 9, 2),
        TypeOfPerson.LEGAL,
        ResourceStatus.active,
        'SP',
        'Santos',
        'Rua Edson Arantes, 10',
        'Vila Belmiro',
        '01594180',
        '',
        13994751310,
        'lucas@teste.com',
        'Financeiro'
    ),
    new ContactModel(
        ++id,
        'Maximiliano Felipe',
        '59024072654',
        new Date(1979, 9, 2),
        TypeOfPerson.NATURAL,
        ResourceStatus.active,
        'SP',
        'Guarujá',
        'Rua Cinqüenta e Sete, 851',
        'Moema',
        '11445540',
        '',
        13984087515,
        'max@teste.com',
        'Comercial'
    )
];
