import { CustomerType } from '../pages/my-customers/shared/enum/customer-type.enum';
import { Customer } from '../pages/my-customers/shared/interface/customer';
import { CustomerModel } from '../pages/my-customers/shared/model/customer-model';
import { ResourceStatus } from '../shared/enum/resource-status.enum';
import { TypeOfPerson } from '../shared/enum/type-of-person.enum';
import { getDateRandom } from './utils';

let id = 0;

export const customers: Customer[] = [
    new CustomerModel(
        ++id,
        1,
        'MADG Marketing ME',
        TypeOfPerson.LEGAL,
        '84696014000181',
        CustomerType.FINAL_COSTUMER,
        'SP',
        'Bragança Paulista',
        'Avenida João Alberto Ahnert, 955',
        'Jardim Águas Claras',
        '12929070',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'Andréia',
        'andreia@madg.com.br',
        1128302252
    ),
    new CustomerModel(
        ++id,
        1,
        'Breadcrumb Padaria ME',
        TypeOfPerson.LEGAL,
        '52299624000155',
        CustomerType.DEALER,
        'AM',
        'Manaus',
        'Rua Praia Canoa Quebrada, 740',
        'Tarumã',
        '69041360',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'Cristiano',
        'cristiano@padariabreadcrumb.com.br',
        9226008589
    ),
    new CustomerModel(
        ++id,
        1,
        'Kibaum Alimentos ME',
        TypeOfPerson.LEGAL,
        '41129289000120',
        CustomerType.DEALER,
        'MG',
        'Timóteo',
        'Rua Sapoti, 802',
        'Nova Esperança',
        '35181102',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'RICARDO',
        'fiscal@kibaumalimento.com',
        3139588567
    ),
    new CustomerModel(
        ++id,
        1,
        'Marcenaria do Manuel Ltda',
        TypeOfPerson.LEGAL,
        '23478793000154',
        CustomerType.FINAL_COSTUMER,
        'MG',
        'Ipatinga',
        'Rua Gênova, 1000',
        'Bethânia',
        '35164055',
        '',
        ResourceStatus.inactive,
        getDateRandom(),
        getDateRandom(),
        'Manuel',
        'mane.marcenaria@marcenariadomanuel.com',
        3126970935
    ),
    new CustomerModel(
        ++id,
        1,
        'CactusMovie Filmagens Ltda',
        TypeOfPerson.LEGAL,
        '97174374000165',
        CustomerType.FINAL_COSTUMER,
        'CE',
        'Maracanaú',
        'Rua 10, 796',
        'Jarí',
        '61916060',
        'Praça da Cidade',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'GERALDO',
        'contato@cactusmovie.com',
        8535083768
    ),
    new CustomerModel(
        ++id,
        1,
        'Três Irmãos Informática ME',
        TypeOfPerson.LEGAL,
        '84870812000188',
        CustomerType.FINAL_COSTUMER,
        'GO',
        'Luziânia',
        'Quadra 94, 206',
        'Mansões de Recreio',
        '72809470',
        'rua da feira de sexta',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'ALAN',
        'alan.carlos@tresirmaosinfo.com.br',
        6136109398
    ),
    new CustomerModel(
        ++id,
        1,
        'Paulo e Aline Tecnologia Ltda',
        TypeOfPerson.LEGAL,
        '80040460000182',
        CustomerType.FINAL_COSTUMER,
        'SP',
        'São Paulo',
        'Rua Luiza Campanella Giordano, 799',
        'Pq Paineiras',
        '03694180',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'PAULETE',
        'paulo@tecnologia.com.br',
        1139749472
    ),
    new CustomerModel(
        ++id,
        1,
        'Mudanças Ursinhos Ltda',
        TypeOfPerson.LEGAL,
        '90054224000179',
        CustomerType.FINAL_COSTUMER,
        'PR',
        'Curitiba',
        'Rua Prof. Maria Balbina C Dias, 283',
        'Boa Vista',
        '82560305',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'BIRO',
        'biro@cavaco.com.br',
        4138325569
    ),
    new CustomerModel(
        ++id,
        1,
        'THOR Ferramentas LTDA',
        TypeOfPerson.LEGAL,
        '78739414000124',
        CustomerType.FINAL_COSTUMER,
        'SP',
        'São Roque',
        'Rua Mariko Karube, 112',
        'Caete (Mailasqui)',
        '18143301',
        'Prox. Estrada do Vinho',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'Trovão',
        'deusdotrovao@thor.com.br',
        1125719512
    ),
    new CustomerModel(
        ++id,
        1,
        'Beatriz Lúcia Sebastiana da Costa',
        TypeOfPerson.NATURAL,
        '79590029833',
        CustomerType.FINAL_COSTUMER,
        'SP',
        'São Paulo',
        'Rua Douglas Moreno dos Santos, 996',
        'Jd. Aurélio',
        '05857245',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'Bia',
        'biazita@email.com',
        1151585851
    ),
    new CustomerModel(
        ++id,
        1,
        'Carlos Heitor Miguel Baptista',
        TypeOfPerson.NATURAL,
        '45633994850',
        CustomerType.RURAL_PRODUCER,
        'SP',
        'Águas de São Pedro',
        'Avenida Washington Luís, 539',
        'Vila Congonhas',
        '04626911',
        'Prox. ao Centro',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'Carlos',
        'carlinhosecarlao@hmail.com',
        1938476002
    ),
    new CustomerModel(
        ++id,
        1,
        'Anderson Kauê Heitor Lopes',
        TypeOfPerson.NATURAL,
        '99823412863',
        CustomerType.FINAL_COSTUMER,
        'SP',
        'São Paulo',
        'Travessa Almarjão, 677',
        'Vila Maria Alta',
        '02136050',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'Anderson',
        'andinholopes@vmail.com',
        1144445555
    ),
    new CustomerModel(
        ++id,
        1,
        'Luís Renato Pedro Ribeiro',
        TypeOfPerson.NATURAL,
        '58167534871',
        CustomerType.FINAL_COSTUMER,
        'SP',
        'São Paulo',
        'Rua Barão de Calera, 659',
        'Parque Cruzeiro do Sul',
        '08070050',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'Luizão',
        'luludeluxemburgo@ameil.com.br',
        1137383837
    ),
    new CustomerModel(
        ++id,
        1,
        'Jennifer Vera Pereira',
        TypeOfPerson.NATURAL,
        '26107997806',
        CustomerType.FINAL_COSTUMER,
        'SP',
        'São Paulo',
        'Viaduto Diario Popular, 242',
        'Centro',
        '01015090',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'JENI',
        'jeniferdotinder@ameil.com.br',
        1137383837
    ),
    new CustomerModel(
        ++id,
        1,
        'Benedita Isabelly Moraes',
        TypeOfPerson.NATURAL,
        '77998490888',
        CustomerType.FINAL_COSTUMER,
        'SP',
        'São Paulo',
        'Rua Jesuíno Antônio Batista, 877',
        'Jardim Guarani',
        '02851080',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'bene',
        'benebenedita@email.com.br',
        1139393939
    ),
    new CustomerModel(
        ++id,
        1,
        'Eduarda Sandra Sabrina Nogueira',
        TypeOfPerson.NATURAL,
        '77998490888',
        CustomerType.FINAL_COSTUMER,
        'SP',
        'São Paulo',
        'Viela da Esperança, 119',
        'Fazenda da Juta',
        '03977470',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'Duda',
        'dudadudu@email.com.br',
        1144445555
    ),
    new CustomerModel(
        ++id,
        1,
        'Augusto e Mariane Contábil ME',
        TypeOfPerson.LEGAL,
        '16639016000189',
        CustomerType.FINAL_COSTUMER,
        'SP',
        'São Paulo',
        'Rua Uberlândia, 475',
        'Vila Polopoli',
        '05365040',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'GUTO',
        'guto@email.com.br',
        1155555555
    ),
    new CustomerModel(
        ++id,
        1,
        'Sacolão -  Meu pé de Laranja Lima',
        TypeOfPerson.LEGAL,
        '01112463000108',
        CustomerType.DEALER,
        'SP',
        'São Paulo',
        'Rua Clamecy, 144',
        'Estância Mirim',
        '04943060',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'PAULO',
        'paulo@email.com.br',
        1155555555
    ),
    new CustomerModel(
        ++id,
        1,
        'Betina Lorena Drumond',
        TypeOfPerson.NATURAL,
        '81107387884',
        CustomerType.FINAL_COSTUMER,
        'SP',
        'São Paulo',
        'Rua Parapuã, 496',
        'Itaberaba',
        '02831001',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'Betina',
        'betina@email.com.br',
        1128310001
    ),
    new CustomerModel(
        ++id,
        1,
        'Pães e Doces Dona Florinda',
        TypeOfPerson.LEGAL,
        '34971954000163',
        CustomerType.DEALER,
        'SP',
        'São Paulo',
        'Rua Eulália Bastos, 221',
        'Tucuruvi',
        '02303020',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'JOZE',
        'jose@email.com.br',
        1123030200
    ),
    new CustomerModel(
        ++id,
        1,
        'Luiza e Maitê Restaurante ME',
        TypeOfPerson.LEGAL,
        '43571746000168',
        CustomerType.DEALER,
        'SP',
        'São Paulo',
        'Rua Baltazar Pereira, 128',
        'Jardim Regina',
        '05175340',
        '',
        ResourceStatus.active,
        getDateRandom(),
        getDateRandom(),
        'Luiza',
        'luiza@email.com.br',
        1151753400
    )
];
