import { SalesItems } from '../pages/my-sales/shared/interfaces/sales-items';

export const salesItems: SalesItems[] = [
  {
      id: 1,
      salesId: 1,
      itemId: 1,
      productId: '0001',
      value: 4.09,
      quantity: 2,
      amount: 8.18,
      productName: '',
      discount: 0
  },
  {
      id: 2,
      salesId: 1,
      itemId: 2,
      productId: '0002',
      value: 4.06,
      quantity: 1,
      amount: 4.06,
      productName: '',
      discount: 0
  },
  {
      id: 3,
      salesId: 1,
      itemId: 3,
      productId: '0003',
      value: 3.49,
      quantity: 3,
      amount: 10.47,
      productName: '',
      discount: 0
  },
  {
      id: 4,
      salesId: 1,
      itemId: 4,
      productId: '0014',
      value: 3.73,
      quantity: 3,
      amount: 11.19,
      productName: '',
      discount: 0
  },
  {
      id: 5,
      salesId: 2,
      itemId: 1,
      productId: '0001',
      value: 4.09,
      quantity: 90,
      amount: 368.1,
      productName: '',
      discount: 0
  },
  {
      id: 6,
      salesId: 2,
      itemId: 2,
      productId: '0005',
      value: 3.99,
      quantity: 400,
      amount: 1596,
      productName: '',
      discount: 0
  },
  {
      id: 7,
      salesId: 2,
      itemId: 3,
      productId: '0002',
      value: 4.06,
      quantity: 35,
      amount: 142.1,
      productName: '',
      discount: 0
  },
  {
      id: 8,
      salesId: 3,
      itemId: 1,
      productId: '0003',
      value: 3.49,
      quantity: 7,
      amount: 24.43,
      productName: '',
      discount: 0
  },
  {
      id: 9,
      salesId: 3,
      itemId: 2,
      productId: '0010',
      value: 2.29,
      quantity: 5,
      amount: 11.45,
      productName: '',
      discount: 0
  },
  {
      id: 10,
      salesId: 3,
      itemId: 3,
      productId: '0004',
      value: 7.49,
      quantity: 1,
      amount: 7.49,
      productName: '',
      discount: 0
  },
  {
      id: 11,
      salesId: 4,
      itemId: 1,
      productId: '0001',
      value: 4.09,
      quantity: 10,
      amount: 40.9,
      productName: '',
      discount: 0
  },
  {
      id: 12,
      salesId: 4,
      itemId: 2,
      productId: '0004',
      value: 7.49,
      quantity: 1,
      amount: 7.49,
      productName: '',
      discount: 0
  },
  {
      id: 13,
      salesId: 4,
      itemId: 3,
      productId: '0006',
      value: 5.39,
      quantity: 2,
      amount: 10.78,
      productName: '',
      discount: 0
  },
  {
      id: 14,
      salesId: 4,
      itemId: 4,
      productId: '0008',
      value: 24.88,
      quantity: 1,
      amount: 24.8,
      productName: '',
      discount: 0
  },
  {
      id: 15,
      salesId: 4,
      itemId: 5,
      productId: '0010',
      value: 2.29,
      quantity: 1,
      amount: 2.29,
      productName: '',
      discount: 0
  },
  {
      id: 16,
      salesId: 4,
      itemId: 6,
      productId: '0011',
      value: 1.79,
      quantity: 3,
      amount: 5.37,
      productName: '',
      discount: 0
  },
  {
      id: 17,
      salesId: 4,
      itemId: 7,
      productId: '0014',
      value: 4.09,
      quantity: 4,
      amount: 16.36,
      productName: '',
      discount: 0
  },
  {
      id: 18,
      salesId: 4,
      itemId: 8,
      productId: '0016',
      value: 4.99,
      quantity: 5,
      amount: 24.95,
      productName: '',
      discount: 0
  },
  {
      id: 19,
      salesId: 4,
      itemId: 9,
      productId: '0017',
      value: 7.9,
      quantity: 2,
      amount: 15.8,
      productName: '',
      discount: 0
  },
  {
      id: 20,
      salesId: 4,
      itemId: 10,
      productId: '0018',
      value: 10.99,
      quantity: 1,
      amount: 10.99,
      productName: '',
      discount: 0
  },
  {
      id: 21,
      salesId: 4,
      itemId: 12,
      productId: '0003',
      value: 3.49,
      quantity: 1,
      amount: 3.49,
      productName: '',
      discount: 0
  },
  {
      id: 22,
      salesId: 4,
      itemId: 13,
      productId: '0002',
      value: 4.06,
      quantity: 12,
      amount: 48.72,
      productName: '',
      discount: 0
  },
  {
      id: 23,
      salesId: 5,
      itemId: 1,
      productId: '0003',
      value: 3.49,
      quantity: 129,
      amount: 450.21,
      productName: '',
      discount: 0
  },
  {
      id: 24,
      salesId: 5,
      itemId: 2,
      productId: '0002',
      value: 4.06,
      quantity: 77,
      amount: 312.62,
      productName: '',
      discount: 0
  },
  {
      id: 25,
      salesId: 5,
      itemId: 3,
      productId: '0012',
      value: 7.49,
      quantity: 4,
      amount: 29.96,
      productName: '',
      discount: 0
  },
  {
      id: 26,
      salesId: 5,
      itemId: 4,
      productId: '0016',
      value: 4.99,
      quantity: 3,
      amount: 14.97,
      productName: '',
      discount: 0
  },
  {
      id: 27,
      salesId: 5,
      itemId: 1,
      productId: '0017',
      value: 7.9,
      quantity: 2,
      amount: 15.8,
      productName: '',
      discount: 0
  },
  {
      id: 28,
      salesId: 6,
      itemId: 1,
      productId: '0001',
      value: 4.09,
      quantity: 5,
      amount: 20.45,
      productName: '',
      discount: 0
  },
  {
      id: 29,
      salesId: 6,
      itemId: 2,
      productId: '0007',
      value: 5.36,
      quantity: 2,
      amount: 10.72,
      productName: '',
      discount: 0
  },
  {
      id: 30,
      salesId: 7,
      itemId: 1,
      productId: '0002',
      value: 4.06,
      quantity: 10,
      amount: 40.6,
      productName: '',
      discount: 0
  },
  {
      id: 31,
      salesId: 7,
      itemId: 2,
      productId: '0001',
      value: 4.09,
      quantity: 30,
      amount: 122.7,
      productName: '',
      discount: 0
  },
  {
      id: 32,
      salesId: 8,
      itemId: 1,
      productId: '0002',
      value: 4.06,
      quantity: 47,
      amount: 190.82,
      productName: '',
      discount: 0
  },
  {
      id: 33,
      salesId: 8,
      itemId: 2,
      productId: '0015',
      value: 3.73,
      quantity: 49,
      amount: 182.77,
      productName: '',
      discount: 0
  },
  {
      id: 34,
      salesId: 9,
      itemId: 1,
      productId: '0018',
      value: 10.99,
      quantity: 3,
      amount: 32.97,
      productName: '',
      discount: 0
  },
  {
      id: 35,
      salesId: 10,
      itemId: 1,
      productId: '0005',
      value: 3.99,
      quantity: 3,
      amount: 11.97,
      productName: '',
      discount: 10
  },
  {
      id: 36,
      salesId: 10,
      itemId: 2,
      productId: '0006',
      value: 5.39,
      quantity: 1,
      amount: 5.39,
      productName: '',
      discount: 0
  },
  {
      id: 37,
      salesId: 10,
      itemId: 3,
      productId: '0007',
      value: 5.36,
      quantity: 3,
      amount: 37.52,
      productName: '',
      discount: 0
  },
  {
      id: 38,
      salesId: 11,
      itemId: 1,
      productId: '0018',
      value: 10.99,
      quantity: 50,
      amount: 549.5,
      productName: '',
      discount: 5
  },
  {
      id: 39,
      salesId: 11,
      itemId: 2,
      productId: '0002',
      value: 4.06,
      quantity: 500,
      amount: 2030,
      productName: '',
      discount: 0
  },
  {
      id: 40,
      salesId: 12,
      itemId: 1,
      productId: '0021',
      value: 115.99,
      quantity: 200,
      amount: 23198,
      productName: '',
      discount: 2
  },
  {
      id: 41,
      salesId: 12,
      itemId: 2,
      productId: '0008',
      value: 24.88,
      quantity: 25,
      amount: 622,
      productName: '',
      discount: 0
  },
  {
      id: 42,
      salesId: 12,
      itemId: 3,
      productId: '0020',
      value: 7.73,
      quantity: 100,
      amount: 773,
      productName: '',
      discount: 0
  },
  {
      id: 43,
      salesId: 12,
      itemId: 4,
      productId: '0024',
      value: 4.26,
      quantity: 50,
      amount: 213,
      productName: '',
      discount: 0
  },
  {
      id: 44,
      salesId: 12,
      itemId: 5,
      productId: '0013',
      value: 5.53,
      quantity: 12,
      amount: 66.33,
      productName: '',
      discount: 0
  },
  {
      id: 45,
      salesId: 12,
      itemId: 6,
      productId: '0023',
      value: 23.03,
      quantity: 500,
      amount: 11515,
      productName: '',
      discount: 0
  },
  {
      id: 45,
      salesId: 2,
      itemId: 4,
      productId: '0037',
      value: 3.59,
      quantity: 500,
      amount: 1795,
      productName: '',
      discount: 0
  },
  {
      id: 46,
      salesId: 2,
      itemId: 5,
      productId: '0024',
      value: 4.26,
      quantity: 79,
      amount: 336.54,
      productName: '',
      discount: 0
  },
  {
      id: 46,
      salesId: 8,
      itemId: 3,
      productId: '0032',
      value: 3.99,
      quantity: 96,
      amount: 383.04,
      productName: '',
      discount: 0.5
  },
  {
      id: 47,
      salesId: 7,
      itemId: 3,
      productId: '0037',
      value: 3.59,
      quantity: 12.5,
      amount: 44.875,
      productName: '',
      discount: 0
  },
  {
      id: 48,
      salesId: 7,
      itemId: 4,
      productId: '0034',
      value: 3.99,
      quantity: 300,
      amount: 1197,
      productName: '',
      discount: 0
  },
  {
      id: 49,
      salesId: 7,
      itemId: 5,
      productId: '0024',
      value: 4.26,
      quantity: 50,
      amount: 213,
      productName: '',
      discount: 0
  }
];
