import { Sales } from '../pages/my-sales/shared/interfaces/sales';
import { SalesStatus } from '../pages/my-sales/shared/interfaces/sales-status.enum';
import { TypeOfFreight } from '../pages/my-sales/shared/interfaces/typeOfFreight.enum';
import { getDateRandom } from './utils';

export const sales: Sales[] = [
  {
      id: 1,
      customerId: 1,
      paymentMethodId: 1,
      paymentConditionsId: 1,
      issueDate: getDateRandom(false, 24, 12),
      carrierId: 1,
      priceListId: 1,
      status: SalesStatus.Closed,
      typeOfFreight: TypeOfFreight.CIF,
      comment: '',
      discount: 0,
      expenses: 0,
      insurance: 0,
      freight: 0
  },
  {
      id: 2,
      customerId: 2,
      paymentMethodId: 3,
      paymentConditionsId: 1,
      issueDate: getDateRandom(false, 20, 1),
      carrierId: 1,
      priceListId: undefined,
      status: SalesStatus.Closed,
      typeOfFreight: TypeOfFreight.FOB,
      comment: '',
      discount: 10,
      expenses: 0,
      insurance: 0,
      freight: 79.94
  },
  {
      id: 3,
      customerId: 1,
      paymentMethodId: 2,
      paymentConditionsId: 1,
      issueDate: getDateRandom(false, 1, 3),
      carrierId: 5,
      priceListId: 1,
      status: SalesStatus.Closed,
      typeOfFreight: TypeOfFreight.CIF,
      comment: '',
      discount: 0,
      expenses: 0,
      insurance: 0,
      freight: 0
  },
  {
      id: 4,
      customerId: 8,
      paymentMethodId: 3,
      paymentConditionsId: 1,
      issueDate: getDateRandom(false, 4, 3),
      carrierId: 2,
      priceListId: 1,
      status: SalesStatus.Blocked,
      typeOfFreight: TypeOfFreight.CIF,
      comment: '',
      discount: 0,
      expenses: 0,
      insurance: 0,
      freight: 0
  },
  {
      id: 5,
      customerId: 3,
      paymentMethodId: 1,
      paymentConditionsId: 1,
      issueDate: getDateRandom(false, 27, 4),
      carrierId: 4,
      priceListId: 1,
      status: SalesStatus.Open,
      typeOfFreight: TypeOfFreight.CIF,
      comment: '',
      discount: 0,
      expenses: 0,
      insurance: 0,
      freight: 127.84
  },
  {
      id: 6,
      customerId: 3,
      paymentMethodId: 2,
      paymentConditionsId: 1,
      issueDate: getDateRandom(false, 14, 5),
      carrierId: 3,
      priceListId: 1,
      status: SalesStatus.Closed,
      typeOfFreight: TypeOfFreight.CIF,
      comment: '',
      discount: 0,
      expenses: 0,
      insurance: 0,
      freight: 300.47
  },
  {
      id: 7,
      customerId: 2,
      paymentMethodId: 1,
      paymentConditionsId: 1,
      issueDate: getDateRandom(false, 13, 6),
      carrierId: 2,
      priceListId: 1,
      status: SalesStatus.Open,
      typeOfFreight: TypeOfFreight.CIF,
      comment: '',
      discount: 10.9,
      expenses: 0,
      insurance: 0,
      freight: 10.9
  },
  {
      id: 8,
      customerId: 4,
      paymentMethodId: 2,
      paymentConditionsId: 1,
      issueDate: getDateRandom(false, 23, 8),
      carrierId: 2,
      priceListId: 1,
      status: SalesStatus.Blocked,
      typeOfFreight: TypeOfFreight.CIF,
      comment: '',
      discount: 19.9,
      expenses: 0,
      insurance: 0,
      freight: 179.39
  },
  {
      id: 9,
      customerId: 5,
      paymentMethodId: 3,
      paymentConditionsId: 1,
      issueDate: getDateRandom(false, 1, 9),
      carrierId: 2,
      priceListId: 1,
      status: SalesStatus.Open,
      typeOfFreight: TypeOfFreight.CIF,
      comment: '',
      discount: 0,
      expenses: 0,
      insurance: 0,
      freight: 0
  },
  {
      id: 10,
      customerId: 6,
      paymentMethodId: 1,
      paymentConditionsId: 1,
      issueDate: getDateRandom(false, 7, 9),
      carrierId: 6,
      priceListId: 1,
      status: SalesStatus.Open,
      discount: 0,
      expenses: 0,
      insurance: 0,
      freight: 0,
      typeOfFreight: TypeOfFreight.SEMFRETE,
      comment: ''
  },
  {
      id: 11,
      customerId: 9,
      paymentMethodId: 6,
      paymentConditionsId: 2,
      issueDate: getDateRandom(false, 12, 10),
      carrierId: 2,
      priceListId: 1,
      status: SalesStatus.Open,
      discount: 0,
      typeOfFreight: TypeOfFreight.SEMFRETE,
      expenses: 0,
      insurance: 59.9,
      freight: 179.9,
      comment: ''
  },
  {
      id: 12,
      customerId: 20,
      paymentMethodId: 7,
      paymentConditionsId: 3,
      issueDate: getDateRandom(false, 13, 10),
      carrierId: 5,
      priceListId: 1,
      status: SalesStatus.Closed,
      discount: 2,
      typeOfFreight: TypeOfFreight.CIF,
      expenses: 79.98,
      insurance: 499.97,
      freight: 398.9,
      comment: ''
  }
];
